name: PR Tests
# This workflow runs on pull requests to check code coverage using Codecov.

permissions:
  contents: read  # Allow the workflow to read repository contents
  pull-requests: write  # Allow the workflow to write to pull requests

on:
  push:
    
    paths:
      - '**/*.rs'  # Run only if there are changes in Rust source files.
env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  CARGO_PROFILE_TEST_DEBUG: 0
  CARGO_PROFILE_RELEASE_LTO: true
  CARGO_PROFILE_RELEASE_CODEGEN_UNITS: 1

jobs:
  coverage:
    name: Codecov Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: Swatinem/rust-cache@v2
        # Cache Rust dependencies to speed up builds
        with:
         cache-all-crates: true  # Cache all crates to avoid re-downloading them
         
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-tarpaulin, cargo-llvm-cov

       
      - name: Generate lockfile
        run: cargo generate-lockfile

      - name: Run tests with coverage
        run: cargo tarpaulin --frozen --all-features --out xml --skip-clean

      - name: Upload to codecov.io
        uses: codecov/codecov-action@v5


        