name: Release Check

on:
  workflow_run:
    workflows: ["PR Tests"]
    types:
      - completed
  push:
    tags:
      - 'v*'

jobs:
  check-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract version tag
        id: version
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          echo "VERSION: ${VERSION}"  # Print the version for debugging
          echo "VERSION: ${VERSION}" >> $GITHUB_ENV

      - name: Read top line of CHANGELOG.md
        id: changelog
        run: |
          changelog_version=$(head -n 1 CHANGELOG.md | grep -oP '^## \d{4}-\d{2}-\d{2} v[0-9]+\.[0-9]+\.[0-9]+')
          echo "changelog_version=${changelog_version}" >> $GITHUB_ENV

      - name: Compare version tag with changelog
        run: |
          echo "Comparing version tag v${VERSION} with changelog version ${changelog_version}"
          if [[ "v${VERSION}" == "${changelog_version}" ]]; then
            echo "Versions match."
          else
            echo "Versions do not match. Failing the release check."
            exit 1
          fi

      - name: Trigger Release Workflows if Versions Match
        if: success()
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.TOD_CONTENTS_READ_WRITE }}
          repository: ${{ github.repository }}
          event-type: trigger-release
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
