name: Release Check

on:
  workflow_run:
    workflows: ["PR Tests"]  # Trigger after the PR tests are completed successfully
    types:
      - completed
  push:
    tags:
      - 'v*'  # Ensure the workflow only runs for version tags (e.g., v1.0.0)

jobs:
  check-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch the latest main branch
        run: |
          git fetch origin main  # Fetch the latest state of the main branch

      - name: Check if CHANGELOG.md has been updated since the last commmit to main.
        id: changelog-check
        run: |
          # Compare the changes in the current branch against the main branch
          if git diff --name-only origin/main...$GITHUB_SHA | grep -q 'CHANGELOG.md'; then
            echo "CHANGELOG.md has been updated."
          else
            echo "CHANGELOG.md has not been updated. Failing the release check."
            exit 1  # Fail the job if CHANGELOG.md hasn't been updated
          fi

      - name: Trigger Release Workflows if CHANGELOG.md Updated
        if: success()  # Only run this step if the previous steps were successful (i.e., CHANGELOG.md updated)
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.TOD_CONTENTS_READ_WRITE }}
          repository: ${{ github.repository }}
          event-type: trigger-release
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
