# .github/workflows/release.yml
# Start Homebrew Releaser when a new GitHub release is created
on:
  release:
    types: [published]
  workflow_dispatch:
    # Allow manual triggering of the workflow
name: Homebrew Release

jobs:
  homebrew-releaser:
      runs-on: ubuntu-latest
      name: Build Homebrew Release
      steps:
        - name: Release project to Homebrew tap
          uses: Justintime50/homebrew-releaser@v2
          with:
            # The name of the homebrew tap to publish your formula to as it appears on GitHub.
            homebrew_owner: stacksjb
            homebrew_tap: homebrew-tod
  
            # The name of the folder in your homebrew tap where formula will be committed to.
            formula_folder: Formula
  
            # The Personal Access Token (saved as a repo secret) that has `repo` permissions for the repo running the action AND Homebrew tap you want to release to. Required.
            github_token: ${{ secrets.TOD_CONTENTS_READ_WRITE }}
  
            # Git author info used to commit to the homebrew tap.s
            commit_owner: Jesse Stanford
            commit_email: stacksjb@users.noreply.github.com
  
            # Install command for your formula.Required
            install: "bin.install 'tod'"

            test: 'assert_match(""Tod #{version}", shell_output("#{bin}/tod -V"))'
  
            target_darwin_amd64: true
            target_darwin_arm64: true
            target_linux_amd64: true
            target_linux_arm64: true
  
            update_readme_table: false
  
            # Skips committing the generated formula to a homebrew tap (useful to verify results on a first run).
            # Default is shown - boolean
            skip_commit: true
  
            # Logs debugging info to console.
            # Default is shown - boolean
            debug: true