name: Release Check

on:
  workflow_run:
    workflows: ["PR Tests"]  # Trigger after the PR tests are completed successfully
    types:
      - completed
  push:
    tags:
      - 'v*'  # Ensure the workflow only runs for version tags (e.g., v1.0.0)

jobs:
  check-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get version tag
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV  # Extract version from the tag (e.g., v0.7.7)

      - name: Check if CHANGELOG.md top line matches the version tag
        id: changelog-check
        run: |
          # Read the top line of CHANGELOG.md
          changelog_version=$(head -n 3 CHANGELOG.md | grep -oP '^## \d{4}-\d{2}-\d{2} v[0-9]+\.[0-9]+\.[0-9]+')
          echo "Top line in CHANGELOG.md: $changelog_version"
          
          # Compare the changelog version with the tag version
          if [[ "$changelog_version" == "## $(date +%Y-%m-%d) v${VERSION}" ]]; then
            echo "CHANGELOG.md has been updated with the correct version."
          else
            echo "CHANGELOG.md top version does not match the tag version. Failing the release check."
            exit 1  # Fail the job if the top line doesn't match the version tag
          fi

      - name: Trigger Release Workflows if CHANGELOG.md Version Matches Tag
        if: success()  # Only run this step if the previous steps were successful (i.e., the changelog version matches the tag)
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.TOD_CONTENTS_READ_WRITE }}  # Replace with GITHUB_TOKEN if needed
          repository: ${{ github.repository }}
          event-type: trigger-release
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
